services:
  mcp-wrapper:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-wrapper:filesystem  # Names the built image
    container_name: mcp-server-filesystem
    user: "${UID:-1000}:${GID:-1000}"  # Run as current user
    ports:
      - "3000:5000" # Bind host port 3000 to docker container port 5000
    volumes:
      # Mount a host directory for persistent data
      - ./mcp-data:/opt/mcp-data
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "http_wrapper.py", "--host", "0.0.0.0", "npx", "-y", "@modelcontextprotocol/server-filesystem", "/opt/mcp-data"]
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
